/* library_project */
import {
  removeAllChildElemByClass,
  removeAllChildElemById,
} from "./removeAllChildElem.js";

import "./style.css";
// const myLibrary = [];

/* Testing out new ideas with IIFE */
// This method has been replaced with the prototypal constructor
// The latter method my preferred method for implementing JavaScript Classes.
// const c = (premsg) => {
//   const msg_prefix = premsg;
//   function out(msg) {
//     console.log(`${msg_prefix} ${msg}`);
//   }
//   function tab(msg) {
//     console.log(`${msg_prefix} Start of table print >>>>>`);
//     console.table(msg);
//     console.log(`${msg_prefix} End of table print   >>>>>`);
//   }
//   function dir(msg) {
//     console.log(`${msg_prefix} Start of object print >>>>`);
//     console.dir(msg);
//     console.log(`${msg_prefix} End of object print   >>>>`);
//   }
//
//   return { out, tab, dir };
// };

// Constructor function
function Con(premsg) {
  let prefix = premsg;

  // Getter function to access private member, prefix
  this.getPreMsg = function () {
    return prefix;
  };
}

// Adding out method to the PROTOTYPE of con Constructor
// These functions prototypes are declared outside of the Function Constructor,
// therefore they don't have access to the private members. That is why the
// 'getter' function, 'getPreMsg' was added.
// src:
//   https://stackoverflow.com/questions/436120/accessing-private-member-variables-from-prototype-defined-functions
Con.prototype.out = function (msg) {
  let preMsg = this.getPreMsg();
  console.log(`${preMsg} ${msg}`);
};

Con.prototype.tab = function (msg, extra = "<empty>") {
  let preMsg = this.getPreMsg();
  console.log(`${preMsg} ${extra} Start of table print >>>>>`);
  console.table(msg);
  // console.log(`${preMsg} ${extra} End of table print   >>>>>`);
};

Con.prototype.dir = function (msg, extra = "<empty>") {
  let preMsg = this.getPreMsg();
  console.log(`${preMsg} ${extra} Start of object print >>>>`);
  console.dir(msg);
  // console.log(`${preMsg} ${extra} End of object print   >>>>`);
};

/**
 * Decided to rewrite Book class. This time it should have the following:
 * 1. a private field (member).
 * 2. a counter to keep track of the number of books. Books created. A static member
 * The book uuid will be generated by the class member itself.
 **/
class Book {
  #uuid;
  #title;
  #author;
  #pages;
  #status;
  constructor(title, author, pages, status) {
    this.#uuid = this.get_new_uuid();
    this.#title = title;
    this.#author = author;
    this.#pages = pages;
    this.#status = status;
    Book.incrementBookCount();
  }
  // Field and methods to keep count of how many books were processed
  static bookCount = 0;

  static incrementBookCount = () => {
    Book.bookCount += 1;
  };

  static get_book_count() {
    return Book.bookCount;
  }

  get_new_uuid() {
    return self.crypto.randomUUID();
  }

  get_uuid() {
    return this.#uuid;
  }

  get_title() {
    return this.#title;
  }

  get_author() {
    return this.#author;
  }

  get_pages() {
    return this.#pages;
  }

  get_status() {
    return this.#status;
  }

  get info() {
    return (
      "uuid: " +
      this.uuid() +
      ", title: " +
      this.title() +
      ", author: " +
      this.author() +
      ", pages: " +
      this.pages() +
      ", status: " +
      this.status()
    );
  }

  set status(stat) {
    this.#status = stat;
  }
}

const bookInfoElements = ["uuid", "title", "author", "pages", "status"];

const valueOf = (bookItem, key) => {
  // Making sure that bookItem is an instance of "Book" class
  if (!(Object.getPrototypeOf(bookItem) === Book.prototype)) {
    return;
  }
  switch (key) {
    case "uuid":
      return bookItem.get_uuid();
    case "title":
      return bookItem.get_title();
    case "author":
      return bookItem.get_author();
    case "pages":
      return bookItem.get_pages();
    case "status":
      return bookItem.get_status();
    default:
      return "";
  }
};

const myLibrary = [
  new Book("The Lord of the Rings", "J.R.R. Tolkien", 1216, "Read"),
  new Book("The Lost Symbol", "Dan Brown", 624, "Read"),
  new Book("Sword of Destiny", "Andrzej Sapkowski", 416, "Unread"),
  new Book("Angels and Demons", "Dan Brown", 396, "Read"),
  new Book("Harry Potter", "J.K. Rowling", 437, "Unread"),
  new Book("Hunger Games Book 1", "Suzanne Collins", 362, "Unread"),
];

// Sample data
// const book1 = new Book("The Lord of the Rings", "J.R.R. Tolkien", 1216, "Read");
// const book2 = new Book("The Lost Symbol", "Dan Brown", 624, "Read");
// const book3 = new Book("Sword of Destiny", "Andrzej Sapkowski", 416, "Unread");
// const book4 = new Book("Angels and Demons", "Dan Brown", 396, "Read");
// const book5 = new Book("Harry Potter", "J.K. Rowling", 437, "Unread");
// const book6 = new Book("Hunger Games Book 1", "Suzanne Collins", 362, "Unread");

function addBookToLibrary(book) {
  myLibrary.push(book);

  // console.log("[addBookLibrary] " + book.get_title());
}

function createElement(elemType, class_list, unique_id, text_content) {
  let element = document.createElement(elemType);

  /* Add class to the element */
  if (!(class_list instanceof Array) && class_list != "") {
    class_list = [class_list];
  }
  if (class_list != "") {
    class_list.forEach((elem) => element.classList.add(elem));
  }

  /* Add id to the element */
  if (unique_id !== "" && !(unique_id === undefined || unique_id === null)) {
    element.setAttribute("id", unique_id);
  }

  /* Add textContent/innerHTML/innerText value */
  if (
    text_content !== "" &&
    text_content !== undefined &&
    text_content !== null
  ) {
    element.textContent = text_content;
  }

  return element;
}

function createCardDiv(bookInfo) {
  // Making sure that bookItem is an instance of "Book" class
  if (!(Object.getPrototypeOf(bookInfo) === Book.prototype)) {
    console.log("[createCardDiv] object is not of Book class");
    return;
  }

  let libCard = createElement("div", "libraryCard");

  bookInfoElements.forEach((infoElements) => {
    // Adding the labels for each card
    let tmpDiv = createElement("div", ["cardRow", infoElements]);

    let lbl = createElement("p", "infoLabel", "", infoElements + ": ");

    // Adding the 'value'/'info' for each card
    let val = 0;
    if (infoElements === "status") {
      val = createElement(
        "button",
        ["button", "infoValue"],
        bookInfo.get_uuid(),
        bookInfo.get_status(),
      );
      val.addEventListener("click", changeBookStat);
    } else {
      let tmpInfo = valueOf(bookInfo, infoElements);
      // console.log("[createCardDiv] tmpInfo: " + tmpInfo);
      val = createElement("p", "infoValue", "", tmpInfo);
    }

    tmpDiv.appendChild(lbl);
    tmpDiv.appendChild(val);

    libCard.appendChild(tmpDiv);
  });

  let tmpDiv = createElement("div", ["cardRow", "buttonRow"]);

  let emptyLbl = createElement("p", "infoLabel", "", " ");

  const tmpBtn = createElement(
    "button",
    ["infoValue"],
    bookInfo.get_uuid(),
    "Remove",
  );
  tmpBtn.addEventListener("click", removeCard);

  tmpDiv.appendChild(emptyLbl);
  tmpDiv.appendChild(tmpBtn);

  libCard.append(tmpDiv);

  // console.log(
  //   "[createCardDiv] Number of books processed: " + Book.get_book_count(),
  // );

  return libCard;
}

function changeBookStat(event) {
  // create a handle for button with matching id
  let tmpBtn = document.getElementById(event.target.id);

  let toggleVar = tmpBtn.innerHTML === "Unread" ? "Read" : "Unread";

  tmpBtn.innerHTML = toggleVar;
  // finding object in array that matches certain criteria
  //   src: https://stackoverflow.com/questions/12462318/find-a-value-in-an-array-of-objects-in-javascript
  myLibrary.find((book, index) => {
    if (book.get_uuid() == event.target.id) {
      myLibrary[index].status = toggleVar;
      console.dir(myLibrary[index]);
    }
  });

  // Determine if the book has been 'read' or 'unread'
  // if (tmpBtn.innerHTML == "Unread") {
  //   tmpBtn.innerHTML = "Read";
  //
  //   myLibrary.find((book, index) => {
  //     if (book.uuid == event.target.id) {
  //       myLibrary[index].status = "Read";
  //       console.log(myLibrary[index]);
  //     }
  //   });
  //   return;
  // }
  // if (tmpBtn.innerHTML == "Read") {
  //   tmpBtn.innerHTML = "Unread";
  //
  //   myLibrary.find((book, index) => {
  //     if (book.uuid == event.target.id) {
  //       myLibrary[index].status = "Unread";
  //       console.log(myLibrary[index]);
  //     }
  //   });
  //   return;
  // }
}

function removeCard(event) {
  console.log("[removeCard] id: " + event.target.id);

  let pos = 0;

  for (; pos < myLibrary.length; pos++) {
    let tmpItem = myLibrary[pos];
    if (tmpItem.get_uuid() == event.target.id) {
      break;
    }
  }
  console.log(`[removeCard] item found in position ${pos}`);
  myLibrary.splice(pos, 1);
  displayInfo();
}

function displayInfo() {
  let content = document.getElementsByClassName("content");

  let child = content[0].lastElementChild;

  while (child) {
    content[0].removeChild(child);
    child = content[0].lastElementChild;
  }

  myLibrary.forEach((bookEntry) => {
    let libCard = createCardDiv(bookEntry);
    content[0].appendChild(libCard);
  });
}

let readBook = document.getElementById("bookStat");
/*
 * NOTE: The example solution suggested attaching the event listener
 *       to 'input' with 'name=checkbox',
 *         let checkbox = document.querySelector("input[name=checkbox]");
 *       Here, the requirement is to return a value of either 'Unread' or 'Read'.
 *       Checkbox will show a value if it is 'checked', otherwise no value
 *       will be shown.
 *       One way to workaround this is to have a type='hidden' input with the
 *       same name as the checkbox intended for. That way if the original checkbox
 *       is 'unchecked' then the hidden input will show up. But if the original
 *       checkbox is 'checked' then the 'hidden' input must be disabled.
 *       Therefore in the html,
 *         <input type="hidden" id="statCheckHidden" name="checkbox" value="Unread">
 *         <input type="checkbox" id="statCheck" name="checkbox" value="Read">
 *       and the eventListenter is attached to the 'id' not the 'name'.
 **/
//
let checkbox = document.getElementById("statCheck");
checkbox.addEventListener("change", function () {
  if (this.checked) {
    readBook.textContent = "Read";
    document.getElementById("statCheckHidden").disabled = true;
  } else {
    readBook.textContent = "Unread";
    document.getElementById("statCheckHidden").disabled = false;
  }
});

const validation = (errorField) => ({
  // custom validation function

  // The following dictionary was created as a customization tool. By making
  // some of the inputs as 'false', the check will not be executed on the
  // input object. So, far after testing going through all the checks is not
  // prohibitive. So, for the moment I'll keeep all the checks as 'true'.
  text_input(obj, msg) {
    let CHECKTYPE = {
      BADINPUT: true,
      CUSTOMERROR: true,
      PATTERNMISMATCH: true,
      RANGEOVERFLOW: true,
      RANGEUNDERFLOW: true,
      STEPMISMATCH: true,
      TOOLONG: true,
      TOOSHORT: true,
      TYPEMISMATCH: true,
      VALUEMISSING: true,
      VALID: true,
    };
    let tmpStr = msg;
    // HTMLInputElement could be a button, text area, text field, checkbox etc..
    // So, the type is checked against "text" to make sure that this function is
    // checking validity against a text box.
    // Latest bug, unable to test for number input. This was corrected with the
    // addition of:
    //   obj.type == "number"
    // The number of pages is of input type of 'number'
    if (
      Object.getPrototypeOf(obj) === HTMLInputElement.prototype &&
      (obj.type == "text" || obj.type == "number")
    ) {
      const inputValidity = obj.validity;
      if (
        inputValidity.badInput &&
        validation.text_input.CHECKTYPE["BADINPUT"]
      ) {
        tmpStr = `Input string for ${msg} could not be converted from a string to a number`;
        console.log(tmpStr);
      }
      if (inputValidity.customError && CHECKTYPE["CUSTOMERROR"]) {
        tmpStr = `There is no custom message set for ${msg}`;
        console.log(tmpStr);
      }
      if (inputValidity.patternMismatch && CHECKTYPE["PATTERNMISMATCH"]) {
        tmpStr = `Input string for ${msg} does not match pattern`;
        console.log(tmpStr);
      }
      if (inputValidity.rangeOverflow && CHECKTYPE["RANGEOVERFLOW"]) {
        tmpStr = `Input string for ${msg} is too long, value greater than max attribute`;
        console.log(tmpStr);
      }
      if (inputValidity.rangeUnderflow && CHECKTYPE["RANGEUNDERFLOW"]) {
        // tmpStr = `Input string for ${msg} is too short, value less than min attribute`;
        tmpStr = `The ${msg} is under 1, must be 1 or higher`;
        console.log(tmpStr);
      }
      if (inputValidity.stepMismatch && CHECKTYPE["STEPMISMATCH"]) {
        tmpStr = `Input string for ${msg} does not conform to the step attribute`;
        console.log(tmpStr);
      }
      // if (inputValidity.tooLong && validation.text_input.CHECKTYPE[TOOLONG]) {
      if (inputValidity.tooLong && CHECKTYPE["TOOLONG"]) {
        tmpStr = `Input string for ${msg} exceeds the maxlength`;
        console.log(tmpStr);
      }
      // if (inputValidity.tooShort && validation.text_input.CHECKTYPE[TOOSHORT]) {
      if (inputValidity.tooShort && CHECKTYPE["TOOSHORT"]) {
        // tmpStr = `Input string for ${msg} is less than the minlength`;
        tmpStr = `The ${msg} must be 3 letters or longer`;
        console.log(tmpStr);
      }
      if (inputValidity.typeMismatch && CHECKTYPE["TYPEMISMATCH"]) {
        tmpStr = `Input string for ${msg} is not the correct format`;
        console.log(tmpStr);
      }
      if (inputValidity.valueMissing && CHECKTYPE["VALUEMISSING"]) {
        tmpStr = `Input string for ${msg} is missing`;
        console.log(tmpStr);
      }
      if (inputValidity.valid && CHECKTYPE["VALID"]) {
        tmpStr = `Input is valid`;
        console.log(tmpStr);
      }
    }
    return tmpStr;
  },
});

/* source: https://stackoverflow.com/questions/10955745/get-values-from-submitted-form
 * NOTE: The solution pointed out above does solve the problem of missing data from
 *       checkbox, if the checkbox weren't 'checked'. But this would not solve the
 *       problem of displaying those changes on the webpage. For that I reverted back
 *       to using the 'change' event above. The 2 'input' is still retained and the
 *       'statCheckHidden' will be disabled when the checkbox is 'checked'.
 *       The values captured will be 'checkbox' or 'checkbox1'.
 **/
let form = document.getElementById("addBookForm");
form.addEventListener("submit", function (e) {
  /*
   * e.preventDefault will prevent the form from submitting.
   * If no errors detected then the form will submit(post action), if not
   * then e.preventDefault will stop the submit process.
   * The original condition for this project was to stop the form from performing
   * 'submit' process. The process is handled here in this function.
   */
  e.preventDefault();
  let bookTitle = document.getElementById("booktitle");
  let bookAuthor = document.getElementById("bookauthor");
  let bookPages = document.getElementById("bookpages");

  const cl = new Con("[form submit]");

  // NOTE: The design for the error message section:
  //         1. Create a space for the error message output
  //         2. Identify all the elements that will contribute to the error messages
  //         3. Establish the conditions that will generate error messages
  //         4. Determine when the code will proceed after checking for input errors
  let tmpErrorSection = document.getElementById("errorMsgSection");
  let errorStr = "";
  let validator = validation();

  if (tmpErrorSection.hasChildNodes()) {
    console.log("Error messages detected");
    removeAllChildElemById(tmpErrorSection);
    tmpErrorSection.classList.remove("errors_detected");
  }

  errorStr = validator.text_input(bookTitle, "book title");
  let bookTitleError =
    errorStr == "Input is valid"
      ? ""
      : createElement("p", ["error", "title"], "titleError", errorStr);
  errorStr = validator.text_input(bookAuthor, "book author");
  let bookAuthorError =
    errorStr == "Input is valid"
      ? ""
      : createElement("p", ["error", "author"], "authorError", errorStr);
  errorStr = validator.text_input(bookPages, "book pages");
  let bookPagesError =
    errorStr == "Input is valid"
      ? ""
      : createElement("p", ["error", "pages"], "pagesError", errorStr);
  // NOTE: The form will not reset and the error messages and tokens will remain on
  //       screen until the user rectifies their input
  if (
    bookTitleError !== "" ||
    bookAuthorError !== "" ||
    bookPagesError !== ""
  ) {
    console.log(
      "[form submit] Error detected, please correct before continuing...",
    );
    // Display the errors here
    let tmpErrorSectionHeading = createElement(
      "p",
      ["error", "heading"],
      "errorSectionHeading",
      "Errors detected, please rectify the inputs",
    );
    // cl.dir(bookPagesError);
    tmpErrorSection.appendChild(tmpErrorSectionHeading);
    if (bookTitleError !== "") {
      tmpErrorSection.appendChild(bookTitleError);
    }
    if (bookAuthorError !== "") {
      tmpErrorSection.appendChild(bookAuthorError);
    }
    if (bookPagesError !== "") {
      tmpErrorSection.appendChild(bookPagesError);
    }
    tmpErrorSection.classList.add("errors_detected");

    return;
  }

  const data = new FormData(form);
  let tmpTitle;
  let tmpAuthor;
  let tmpPages;
  let tmpStat;
  for (const [name, value] of data) {
    if (name == "title") {
      tmpTitle = value;
    }
    if (name == "author") {
      tmpAuthor = value;
    }
    if (name == "pages") {
      tmpPages = value;
    }
    if (name == "checkbox") {
      tmpStat = value;
    }
  }
  let tmpBook = new Book(tmpTitle, tmpAuthor, tmpPages, tmpStat);

  addBookToLibrary(tmpBook);
  displayInfo();
  form.reset();
  let para = document.getElementById("bookStat");
  para.textContent = "Unread";
});

function bookFormEvent(event) {
  // console.dir(this);
  var isOpen = formContainer.classList.contains("slide-in");

  formContainer.setAttribute("class", isOpen ? "slide-out" : "slide-in");
  if (this.textContent === "Show Book Form") {
    document.getElementById("addBookBtn").innerHTML = "Hide Book Form";
    return;
  }
  if (this.textContent === "Hide Book Form") {
    this.innerHTML = "Show Book Form";
    // form.reset();
    document.getElementById("addBookForm").reset();
    return;
  }
}

// bookTitle.addEventListener("click", inputValidatorCustomError);
// bookAuthor.addEventListener("click", inputValidatorCustomError);

var formContainer = document.getElementById("formContainer");
let addBookbtn = document.getElementById("addBookBtn");
addBookBtn.addEventListener("click", bookFormEvent);

displayInfo();
